name: Build, Upload, Policy Management, Deploy and Rollback Mule App

on:
  push:
    branches:
      - 'develop'      # dev environment
      - 'release/**'   # uat environment
      - 'master'       # prod environment
  workflow_dispatch:

env:
  JAVA_VERSION: '17'																																	 

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.ref, 'refs/heads/release/') && 'uat' || (github.ref == 'refs/heads/master' && 'prod' || 'dev') }}
    env:
      TARGET_ENV: ${{ startsWith(github.ref, 'refs/heads/release/') && 'uat' || (github.ref == 'refs/heads/master' && 'prod' || 'dev') }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}                                            

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Debug secrets
        run: |
          echo "ORG_ID length: ${#ORG_ID}"
          echo "CLIENT_ID length: ${#CONNECTED_APP_CLIENT_ID}"
          echo "CLIENT_SECRET length: ${#CONNECTED_APP_CLIENT_SECRET}"
          echo "NEXUS_USERNAME length: ${#NEXUS_USERNAME}"                                                
        env:
          ORG_ID: ${{ secrets.ORG_ID }}
          CONNECTED_APP_CLIENT_ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
          CONNECTED_APP_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}                                             

      - name: Compute dynamic app name
        run: |
          ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
          if [ "${TARGET_ENV}" = "dev" ]; then PREFIX="bosdev"; elif [ "${TARGET_ENV}" = "uat" ]; then PREFIX="bosuat"; else PREFIX="bos"; fi
          APP_NAME="${PREFIX}-${ARTIFACT_ID}"
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "Using APP_NAME=$APP_NAME"

      # Give this run a unique version so Exchange doesn't reject duplicates
      - name: Set CI version (unique per run)
        run: |
          BASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          NEW_VERSION="${BASE_VERSION}-${GITHUB_RUN_NUMBER}"
          mvn -B versions:set -DnewVersion="${NEW_VERSION}" -DgenerateBackupPoms=false -DprocessDependencies=false
          echo "Using version: ${NEW_VERSION}"
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Print effective-settings (optional)
        run: mvn -B help:effective-settings -s .maven/settings.xml

      # Build but skip MUnit tests here
      - name: Build with Maven
        run: mvn -B clean package -s .maven/settings.xml -DskipMunitTests -Danypoint.organization=${{ secrets.ORG_ID }} -Denv=${{ env.TARGET_ENV }} -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" -Ddecryption.key="${{ secrets.DECRYPTION_KEY }}" -Dnexus.username="${{ secrets.NEXUS_USERNAME }}" -Dnexus.password="${{ secrets.NEXUS_PASSWORD }}" -Dapp.name="${APP_NAME}"

      - name: Stamp artifact file name with commit hash
        shell: bash
        run: |
          artifactName1=$(ls target/*.jar | head -1)
          commitHash=$(git rev-parse --short "$GITHUB_SHA")
          artifactName2="${artifactName1%.jar}-$commitHash.jar"
          mv "$artifactName1" "$artifactName2"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-artifact
          path: target/*.jar
          if-no-files-found: error
          retention-days: 7

  # Uncomment when Nexus credentials are available
  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment: ${{ startsWith(github.ref, 'refs/heads/release/') && 'uat' || (github.ref == 'refs/heads/master' && 'prod' || 'dev') }}
  #   env:
  #     TARGET_ENV: ${{ startsWith(github.ref, 'refs/heads/release/') && 'uat' || (github.ref == 'refs/heads/master' && 'prod' || 'dev') }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/cache@v4
  #       with:
  #         path: ~/.m2/repository
  #         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
  #     - uses: actions/setup-java@v4
  #       with:
  #         java-version: ${{ env.JAVA_VERSION }}
  #         distribution: 'temurin'
  #     - name: Compute dynamic app name
  #       run: |
  #         ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
  #         if [ "${TARGET_ENV}" = "dev" ]; then PREFIX="bosdev"; elif [ "${TARGET_ENV}" = "uat" ]; then PREFIX="bosuat"; else PREFIX="bos"; fi
  #         APP_NAME="${PREFIX}-${ARTIFACT_ID}"
  #         echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
  #     - name: Run MUnit Tests
  #       run: mvn -B clean test -s .maven/settings.xml -DmuleVersion=4.9.0 -Dmunit.runtime.version=4.9.0 -Denv=${{ env.TARGET_ENV }} -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" -Dapp.name="${APP_NAME}"
  #     - name: Upload MUnit Reports
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: munit-reports
  #         path: target/munit-reports/**
  #         if-no-files-found: warn
  #         retention-days: 7

  upload:
    needs: [build]  # add 'test' later when enabled
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.ref, 'refs/heads/release/') && 'uat' || (github.ref == 'refs/heads/master' && 'prod' || 'dev') }}
    env:
      TARGET_ENV: ${{ startsWith(github.ref, 'refs/heads/release/') && 'uat' || (github.ref == 'refs/heads/master' && 'prod' || 'dev') }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}                                            

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - uses: actions/download-artifact@v4
        with:
          name: mule-artifact
          path: .

      - name: Set CI version
        run: |
          BASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          NEW_VERSION="${BASE_VERSION}-${GITHUB_RUN_NUMBER}"
          mvn -B versions:set -DnewVersion="${NEW_VERSION}" -DgenerateBackupPoms=false -DprocessDependencies=false
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Upload to Exchange
        run: mvn -B deploy -s .maven/settings.xml -DskipMunitTests -Danypoint.organization=${{ secrets.ORG_ID }} -Denv=${{ env.TARGET_ENV }} -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" -Ddecryption.key="${{ secrets.DECRYPTION_KEY }}" -Dnexus.username="${{ secrets.NEXUS_USERNAME }}" -Dnexus.password="${{ secrets.NEXUS_PASSWORD }}" -Dapp.name="${APP_NAME}"

  policy-management:
    needs: upload
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.ref, 'refs/heads/release/') && 'uat' || (github.ref == 'refs/heads/master' && 'prod' || 'dev') }}
    env:
      TARGET_ENV: ${{ startsWith(github.ref, 'refs/heads/release/') && 'uat' || (github.ref == 'refs/heads/master' && 'prod' || 'dev') }}
      ANYPOINT_CLIENT_ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
      ANYPOINT_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
      ANYPOINT_ORG: ${{ secrets.ORG_ID }}
      ANYPOINT_ENV: ${{ startsWith(github.ref, 'refs/heads/release/') && 'uat' || (github.ref == 'refs/heads/master' && 'prod' || 'dev') }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Anypoint CLI + jq
        run: |
          npm install -g anypoint-cli-v4
          sudo apt-get update && sudo apt-get install -y jq

      - name: Debug CLI session
        run: |
          anypoint-cli-v4 --version
          anypoint-cli-v4 user:whoami || true

      - name: Compute API Name & Version
        run: |
          ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
          if [ "${TARGET_ENV}" = "dev" ]; then PREFIX="bosdev"; elif [ "${TARGET_ENV}" = "uat" ]; then PREFIX="bosuat"; else PREFIX="bos"; fi
          API_NAME="${PREFIX}-${ARTIFACT_ID}"
          API_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "API_NAME=$API_NAME" >> $GITHUB_ENV
          echo "API_VERSION=$API_VERSION" >> $GITHUB_ENV

      - name: Ensure API instance exists in API Manager
        run: |
          API_EXISTS=$(anypoint-cli-v4 api-mgr api list --organization "$ANYPOINT_ORG" --environment "$ANYPOINT_ENV" --output json | jq -r --arg name "$API_NAME" '.[] | select(.name==$name) | .id')
          if [ -z "$API_EXISTS" ]; then
            echo "API not found. Creating new one: $API_NAME"
            API_EXISTS=$(anypoint-cli-v4 api-mgr api create --organization "$ANYPOINT_ORG" --environment "$ANYPOINT_ENV" --name "$API_NAME" --asset-id "$API_NAME" --version "1.0.0" --type http --endpoint '{"isCloudHub":true,"muleVersion4OrAbove":true,"deploymentType":"CLOUDHUB"}' --output json | jq -r '.id')
          else
            echo "API already exists with ID $API_EXISTS"
          fi
          echo "API_INSTANCE_ID=$API_EXISTS" >> $GITHUB_ENV
          echo "$API_EXISTS" > .api_instance_id.txt

															 
      - uses: actions/upload-artifact@v4
        with:
          name: api-instance-id
          path: .api_instance_id.txt

      - name: Apply Client ID Enforcement Policy
        run: |
          echo "Applying Client ID Enforcement policy to API $API_INSTANCE_ID in env $ANYPOINT_ENV"
          anypoint-cli-v4 api-mgr policy apply --organization "$ANYPOINT_ORG" --environment "$ANYPOINT_ENV" --api-id "$API_INSTANCE_ID" --policy client-id-enforcement --policy-parameters '{"credentialsOrigin":"HTTP_BASIC_AUTHORIZATION_HEADER"}'

  deploy:
    needs: policy-management
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.ref, 'refs/heads/release/') && 'uat' || (github.ref == 'refs/heads/master' && 'prod' || 'dev') }}
    env:
      TARGET_ENV: ${{ startsWith(github.ref, 'refs/heads/release/') && 'uat' || (github.ref == 'refs/heads/master' && 'prod' || 'dev') }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - uses: actions/download-artifact@v4
        with:
          name: mule-artifact
          path: .

      # Ensure the same unique version is set here too
      - name: Set CI version (unique per run)
        run: |
          BASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          NEW_VERSION="${BASE_VERSION}-${GITHUB_RUN_NUMBER}"
          mvn -B versions:set -DnewVersion="${NEW_VERSION}" -DgenerateBackupPoms=false -DprocessDependencies=false
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Deploy to CloudHub 2.0
        run: mvn -B deploy -s .maven/settings.xml -DmuleDeploy -DskipMunitTests -Danypoint.organization=${{ secrets.ORG_ID }} -Denv=${{ env.TARGET_ENV }} -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" -Ddecryption.key="${{ secrets.DECRYPTION_KEY }}" -Dapp.name="${APP_NAME}"

      - name: Save version & API instance
        if: success()
        run: echo "${NEW_VERSION}" > .last_version.txt

      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: last-successful-version
          path: .last_version.txt

      - uses: actions/download-artifact@v4
        if: success()
        with:
          name: api-instance-id
          path: .

  rollback:
    needs: deploy
    if: failure()
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.ref, 'refs/heads/release/') && 'uat' || (github.ref == 'refs/heads/master' && 'prod' || 'dev') }}
    env:
      TARGET_ENV: ${{ startsWith(github.ref, 'refs/heads/release/') && 'uat' || (github.ref == 'refs/heads/master' && 'prod' || 'dev') }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      ANYPOINT_CLIENT_ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
      ANYPOINT_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
      ANYPOINT_ORG: ${{ secrets.ORG_ID }}
      ANYPOINT_ENV: ${{ startsWith(github.ref, 'refs/heads/release/') && 'uat' || (github.ref == 'refs/heads/master' && 'prod' || 'dev') }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: last-successful-version
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: api-instance-id
          path: .

      - name: Install Anypoint CLI
        run: npm install -g anypoint-cli-v4

      - name: Debug CLI session
        run: |
          anypoint-cli-v4 --version
          anypoint-cli-v4 user:whoami || true

      - name: Rollback to Previous Version and Re-Apply Policy
        run: |
          PREVIOUS_VERSION=$(cat .last_version.txt)
          API_INSTANCE_ID=$(cat .api_instance_id.txt)
          echo "Rolling back to version $PREVIOUS_VERSION (API $API_INSTANCE_ID)"
          mvn -B mule:deploy -s .maven/settings.xml -DmuleDeploy -Danypoint.organization=${{ secrets.ORG_ID }} -Denv=${{ env.TARGET_ENV }} -Dapplication.version=$PREVIOUS_VERSION -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" -Ddecryption.key="${{ secrets.DECRYPTION_KEY }}" -Dnexus.username="${{ secrets.NEXUS_USERNAME }}" -Dnexus.password="${{ secrets.NEXUS_PASSWORD }}" -Dapp.name="${APP_NAME}"
          # Ensure rollback still enforces policy
          anypoint-cli-v4 api-mgr policy apply --organization "$ANYPOINT_ORG" --environment "$ANYPOINT_ENV" --api-id "$API_INSTANCE_ID" --policy client-id-enforcement --policy-parameters '{"credentialsOrigin":"HTTP_BASIC_AUTHORIZATION_HEADER"}'
